//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company()
        {
            this.documents = new HashSet<document>();
            this.PersonEntities = new HashSet<PersonEntity>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> established_date { get; set; }
        public string company_address { get; set; }
        public string website_url { get; set; }
        public string email_address { get; set; }
        public string country { get; set; }
        public Nullable<int> industry_id { get; set; }
        public Nullable<int> sector_id { get; set; }
        public Nullable<bool> is_blacklisted { get; set; }
    
        public virtual industry industry { get; set; }
        public virtual sector sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document> documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonEntity> PersonEntities { get; set; }
    }
}
