//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonEntity
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> linked_company_id { get; set; }
        public Nullable<bool> is_hit { get; set; }
        public Nullable<int> risk_rating { get; set; }
        public string santion_source { get; set; }
    
        public virtual company company { get; set; }
    }
}
