//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class subEntity
    {
        public int id { get; set; }
        public Nullable<int> mainEntity_id { get; set; }
        public Nullable<int> entityType_id { get; set; }
        public string name { get; set; }
    
        public virtual entityType entityType { get; set; }
        public virtual mainEntity mainEntity { get; set; }
    }
}
